language: node_js
notifications: 
    - geison.sn@gmail.com
node_js:
    - 5.9.1
services:
    - mongodb
env:
    global:
        - NODE_ENV: test
addons:
    sauce_connect: true
before_install:
    - npm install -g bower@1.5.2
    - npm install -g grunt-cli@1.2.0
    - npm install -g karma-cli@1.0.1
    - npm install -g protractor@4.0.9
    - webdriver-manager update
    - bower install
bebore_script:
    - node test/data.js
    - grunt
    - cd dist
script:
    - karma start config/karma.config.js --single-run --browsers PhantomJS
    - node server &
    - protractor config/protractor.js
